# This is a basic workflow to help you get started with Actions

name: Test Module

# Controls when the workflow will run
on:
  # Triggers the workflow on release:created
  release:
    types: [created]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  fetch:
    runs-on: ubuntu-latest
    container: alpine:latest
    steps:
      - name: Obtain Latest Git ONLY within container for checkout
        run: apk add git --update-cache

      - name: Checkout Repo Action
        uses: actions/checkout@v2
  test:
    needs: fetch
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl-version:
          - '5.20'
          
    container:
      image: perl:${{ matrix.perl-version }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:        
      - name: Fix ExtUtils::MakeMaker (for Perl 5.16 and 5.18)
        run: cpanm -n App::cpanminus ExtUtils::MakeMaker
          
      - name: List files
        run: |
          ls -al
        
      - name: "Installing dependencies and testing all using dzil"
        uses: jonasbn/github-action-perl-dist-zilla@0.2.0
        with:
          entrypoint: ./.github/entrypoint.sh
          dzil-arguments: 'test --all'
