# This is a basic workflow to help you get started with Actions

name: Test Module

# Controls when the workflow will run
on:
  # Triggers the workflow on release:created
  release:
    types: [created]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl-version:
          - '5.20'
          
    container:
      image: perl:${{ matrix.perl-version }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: Fix ExtUtils::MakeMaker (for Perl 5.16 and 5.18)
        run: cpanm -n App::cpanminus ExtUtils::MakeMaker
          
      - name: Install dependencies
        run: |
          ls
          dzil authordeps --missing | cpanm
          dzil listdeps | cpanm
        
      - name: "Installing dependencies and testing all using dzil"
        uses: jonasbn/github-action-perl-dist-zilla@0.2.0
        with:
          dzil-arguments: 'test --all'
